version: '3.9'
name: "bip-frontend-staging"
services:
  frontend:
    container_name: frontend-staging
    restart: on-failure
    build:
        context: .
        dockerfile: Dockerfile-staging
    expose:
      - '3000' # Only expose port to Nginx service

  nginx:
    container_name: nginx-frontend-staging
    restart: on-failure
    build:
        context: ./nginx_container
        dockerfile: Dockerfile-staging
    ports:
      - '3008:3008'
    depends_on:
    - frontend
    volumes:
      - y:/bip_backend_assets_development/user:/static/user
