FROM node:lts as dependencies
WORKDIR /my-project
COPY ../package.json yarn.lock ./
RUN yarn install --frozen-lockfile

FROM node:lts as builder
WORKDIR /my-project
COPY . .

# Clobber development configuration file
COPY ./modules/config-production.ts ./modules/config.ts

COPY --from=dependencies /my-project/node_modules ./node_modules
ENV NEXT_TELEMETRY_DISABLED 1
RUN yarn build

FROM node:lts as runner
WORKDIR /my-project

# If you are using a custom next.config.js file, uncomment this line.
COPY --from=builder /my-project/next.config.js ./
COPY --from=builder /my-project/next-i18next.config.js ./
COPY --from=builder /my-project/public ./public
COPY --from=builder /my-project/.next ./.next
COPY --from=builder /my-project/node_modules ./node_modules
COPY --from=builder /my-project/package.json ./package.json

CMD ["yarn", "start"]
