# Install dependencies only when needed
FROM node:lts as deps
WORKDIR /app
COPY ../package.json yarn.lock ./
RUN yarn install --frozen-lockfile

# Rebuild the source code only when needed
FROM node:lts as builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY ../. .
ENV NEXT_TELEMETRY_DISABLED 1
RUN yarn build

# Copy all the files and run next
FROM node:lts as runner
WORKDIR /app

ENV NODE_ENV development

COPY --from=builder /app/next.config.js ./
COPY --from=builder /app/next-i18next.config.js ./
COPY --from=builder /app/public ./public
COPY --from=builder /app/.next ./.next
COPY --from=builder /app/node_modules ./node_modules
COPY --from=builder /app/package.json ./package.json

CMD ["yarn", "start"]
